# Generated by Django 3.0.5 on 2020-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0007_auto_20200608_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
